#!/bin/sh

bspc config border_width        2
bspc config window_gap          5

bspc monitor HDMI2 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10

bspc config apply_floating_atom true
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#519f50"
bspc config presel_border_color "#da4939"

bspc rule -a "crx_nckgahadagoaajjgafhacjanaoiihapd" floating=on center=false
bspc rule -a Chromium desktop=^6
bspc rule -a Steam floating=true
bspc rule -a \* center=true

${HOME}/.config/bspwm/panel/panel &
