#!/bin/sh

bspc config border_width        2
bspc config window_gap          5

bspc monitor HDMI2 -d i ii iii iv v
bspc monitor HDMI1 -d vi vii viii ix x

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc rule -a Chromium desktop=^6

${HOME}/.config/bspwm/panel/panel &
