#!/bin/sh

source $(dirname $0)/panel.cfg

(echo " $@"; sleep $NOTIFY_DURATION) \
  | bar \
        -g "$NOTIFY_GEOMETRY" \
        -f "$PANEL_FONT_FAMILY" \
        -F "$FG_BASE" \
        -B "$BG_BASE" \
        -u "$LINEHEIGHT"
