#! /bin/sh
#
# Example panel for LemonBoy's bar

source $(dirname $0)/panel.cfg

while read -r line ; do
  case $line in
    S*)
      # clock output
      SYSTEM_INFO="%{r}${line#?} "
      ;;
    W*)
      # bspwm internal state
      WM_INFO=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          O*)
            # Focused, occupied desktop
            WM_INFO="${WM_INFO}${ICON_OCCUPIED_FOCUSED}"
            ;;
          F*)
            # Focused, empty desktop
            WM_INFO="${WM_INFO}${ICON_EMPTY_FOCUSED}"
            ;;
          U*)
            # Focused, urgent desktop
            WM_INFO="${WM_INFO}%{B$BG_URGENT}%{F$FG_URGENT}${ICON_OCCUPIED_FOCUSED}%{B$BG_TAGS}%{F$FG_TAGS}"
            ;;
          o*)
            # Occupied desktop
            WM_INFO="${WM_INFO}%{A:bspc desktop -f ${name}:}$ICON_OCCUPIED%{A}"
            ;;
          f*)
            # Empty desktop
            WM_INFO="${WM_INFO}%{A:bspc desktop -f ${name}:}$ICON_EMPTY%{A}"
            ;;
          u*)
            # Urgent desktop
            WM_INFO="${WM_INFO}%{A:bspc desktop -f ${name}:}%{B$BG_URGENT}$ICON_OCCUPIED%{B$BG_TAGS}%{F$FG_TAGS}%{A}"
            ;;
          L*)
            # Layout
            LAYOUT="%{B$BG_MONOCLE}%{F$FG_MONOCLE}$(printf "%s" "$(echo ${name} |sed 's/tiled//g' |sed 's/monocle/%{A:bspc desktop -l next:} (Click to exit Monocle) %{A}/g')")%{B-}%{F-}"
            WM_INFO="%{B$BG_LAUNCHER}%{F$FG_LAUNCHER}%{A:$CMD_LAUNCHER:}$ICON_LAUNCHER%{A}%{B$BG_TAGS}%{F$FG_TAGS}${WM_INFO} "
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "${WM_INFO}${LAYOUT}${SYSTEM_INFO}"
done
