#!/bin/bash

source $(dirname $0)/panel.cfg

TEMPERATURE=$(sensors | grep "Physical id 0" | awk '{print $4}' | sed s/+//)

if [[ $TEMPERATURE > "49" ]]; then
  OUTPUT="%{F$COLOR_ICON}  %{F-}$TEMPERATURE"
else
  OUTPUT=""
fi

echo $OUTPUT;
